name: Catalog Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'catalog-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'catalog-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./catalog-service

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Build Docker image
      run: docker build -t catalog-service .

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag catalog-service ${{ secrets.DOCKER_HUB_USERNAME }}/catalog-service:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/catalog-service:latest